START TRANSACTION

----------------------------------- News -----------------------------------

INSERT INTO news(id, submittedon, title, newstext) VALUES (1, '2013-06-18 00:00:00.000', 'Gov’t Mule', 'Southern Rock vom Feinsten erwartet die Besucher des Wiener W.U.K. am Freitag, 12. Juli, wenn sich Ausnahme-Songwriter und –Slidegitarrist Warren Haynes mit seiner Band Gov’t Mule die Ehre gibt.');
INSERT INTO news(id, submittedon, title, newstext) VALUES (2, '2013-06-18 00:00:00.000', 'La Bohème', 'Giacomo Puccinis Meisterwerk im Römersteinbruch! Mit "La Bohème" bringen die Opernfestspiele St. Margarethen vom 10. Juli bis 25. August 2013 ein berauschendes Operndrama auf die Bühne.');
INSERT INTO news(id, submittedon, title, newstext) VALUES (3, '2013-06-30 00:00:00.000', 'Leben ohne Müll', 'Ein Leben ohne Müll? Dorothea Kocsis hat diesen Versuch erfolgreich realisiert – durch Vermeiden, Wiederverwenden und Recyceln konnte sie alles, was in ihrem Fünf-Personen-Haushalt an Müll anfällt, schrittweise reduzieren. Mit geändertem Einkaufsverhalten schlägt sie dem Konsumwahn ein Schnippchen und gewinnt vor allem eines: Zeit und Energie. Frei nach dem Motto: Der Einkaufsweg ist das Ziel, slow shopping – slow-littering – slow-living!');
INSERT INTO news(id, submittedon, title, newstext) VALUES (4, '2013-06-30 00:00:00.000', 'Gironcoli: Context', 'Die Schau im Belvedere wird keine herkömmliche Retrospektive sein, sondern das Werk Bruno Gironcolis erstmalig in ein Netzwerk von Beziehungen zu klassischen wie zu wichtigen zeitgenössischen Positionen stellen.');
INSERT INTO news(id, submittedon, title, newstext) VALUES (5, '2013-07-05 00:00:00.000', 'Toni Innauer - Am Puls des Erfolgs und kritische Punkte', 'Toni Innauer liest aus seinen beiden Bestsellern und erzählt brandaktuelle und nostalgisch humorvolle Episoden aus der jahrzehntelang erfolgreichen Kultur des Österreichischen Skisprungsports. Die Superadler und ihre Vorgänger sind der fliegende Beweis dafür, dass man mit den Weltbesten mithalten kann, wenn der "Spirit auf excellence" gelebt wird und faire Spielregeln bewusst gepflegt werden. Der Spitzensport spiegelt aber auch gnadenlos die belastenden Entwicklungen, die wir alle im Wirtschafts- und Berufsleben erfahren, wenn beim Kampf um Erfolg und Marktanteile das gesunde Augenmaß verloren geht und Gier die Oberhand gewinnt.');
INSERT INTO news(id, submittedon, title, newstext) VALUES (6, '2013-07-08 00:00:00.000', 'Ein Sommernachtstraum', 'Die romantischen Gärten von Schloss Pötzleinsdorf werden für Shakespeares vielleicht beste Komödie zu den Wäldern rund um Athen. Das Stück verfolgt die abenteuerlichen Erlebnisse vier junger Liebender, die nachts aus dem engen Korsett des Athener Hoflebens in die Freiheit der Wälder ausbrechen. Doch der Wald ist auch Heimat der Feenkönigin Titania, ihrem Gemahl Oberon und seinem treuem Begleiter Puck. Die Feenwelt ist nach einem Streit zwischen Oberon und Titania aus den Fugen geraten und als sich zu den mythischen Elfen die Liebenden und schließlich auch noch eine Gruppe Amateurschauspieler gesellen, ist das Chaos perfekt.');
INSERT INTO news(id, submittedon, title, newstext) VALUES (7, '2013-07-08 00:00:00.000', 'Elfie Semotan', 'Die Grenzen zwischen Werbefotografie und künstlerischer Fotografie sind in der Arbeit von Elfie Semotan, die Künstler wie Martin Kippenberger inspirierte, fließend. Dass von Elfie Semotan daher nicht als Modefotografin im klassischen Sinne gesprochen werden kann, führt die Schau eindrucksvoll vor Augen. Elfie Semotan (*1941), die Grande Dame der österreichischen Fotografie, arbeitete nach ihrer Ausbildung als Modedesignerin jahrelang als Modell, bevor sie Ende der 1960er-Jahre hinter die Kamera wechselte und mit ihren lyrischen Modefotografien internationalen Ruhm erlangte.');
INSERT INTO news(id, submittedon, title, newstext) VALUES (8, '2013-07-08 00:00:00.000', 'Pacific Rim (Kinostart: 18. Juli 2013)', 'Fremdartige und monströse Kreaturen, die als Kaiju bekannt sind und aus den Tiefen des Pazifischen Ozeans emporsteigen, haben in einem Krieg bereits Millionen Menschenleben gefordert. Sogar eine Atombombe konnte die außerirdischen Wesen nicht stoppen. Um die Kaiju zu besiegen, entwickelten zwei Wissenschaftler überdimensionale Roboter, die "Jäger", welche von zwei Piloten durch eine neurale Brücke gesteuert werden. Doch selbst die Jäger scheinen nicht gegen die außerirdische Macht anzukommen. Mit ihren letzten beiden Verteidigern, dem abgehalfterten Ex-Piloten Raleigh Becket (Charlie Hunnam) und der unerfahrenen Novizin Mako Mori (Rinko Kikuchi) holt die Menschheit zum alles entscheidenden Schlag gegen die Kaiju aus. Mit Unterstützung von Makos Adoptivvater, dem legendären britischen Jäger-Piloten Stacker Pentecost (Idris Elba), begibt sich das ungleiche Duo auf die gefährliche Mission, um die Menschheit vor dem Ende zu bewahren.');
INSERT INTO news(id, submittedon, title, newstext) VALUES (9, '2013-07-08 00:00:00.000', 'Wolverine: Weg des Kriegers  (Kinostart: 08. August 2013)', 'Logan (Hugh Jackman), auch bekannt als der Mutant Wolverine, wird unter zwielichtigen Umständen nach Japan gelockt, welches er seit dem zweiten Weltkrieg nicht mehr betreten hat. In einer Welt von Smaurai und Yakuza findet er sich unerwartet auf der Flucht mit einer ebenso schönen wie mysteriösen Erbin wieder. Zum ersten Mal wird er mit der Aussicht auf Sterblichkeit konfrontiert, in einer Zeit in der er an seine emotionalen und physischen Grenzen gedrückt wird. Er ist nicht nur gezwungen gegen den übermächtigen Gegner und seinen größten Erzfeind, Silver Samurai (Will Yun Lee), anzukämpfen, sondern auch gegen die Schatten seiner Vergangenheit. Während er versucht seinen Gegner trotz des tödlichen Samurai-Stahls zu besiegen muss er gleichzeitig einen eigenen inneren Kampf gegen seine Existenz als Mutant ausfechten. Doch an jedem aussichtslos erscheinenden Problem wächst er und wird dadurch letztendlich stärker als jemals zuvor.');
INSERT INTO news(id, submittedon, title, newstext) VALUES (10, '2013-07-09 00:00:00.000', 'Veronica Mars', 'Veronica Mars kehrt groß zurück: Vom Fernseher schafft sie den Sprung auf die Leinwand. Die Serie, die es im Fernsehen nur auf drei Staffeln brachte, handelt von der Teenagerin Veronica Mars, die tagsüber die Schulbank drückt und nachts als Detektivin arbeitet. Dank einer der erfolgreichsten Kickstarter-Kampagnen konnte nun mit Hilfe von mehr als 90000 Fans ein Film produziert werden, der im März 2014 in die Kinos kommen wird.');

INSERT INTO employee(firstname, lastname, username, passwordhash, isadmin, wrongPasswordCounter) VALUES('Marvin', 'Jones', 'marvin', '$2a$10$8WiKEL99icp/o/yRZkjCSO1aTLS/S4KJ5blSm9nq90fre82lBamnK', true, 0);
INSERT INTO employee(firstname, lastname, username, passwordhash, isadmin, wrongPasswordCounter) VALUES('Manuela', 'Oster', 'm.oster', '$2a$10$8WiKEL99icp/o/yRZkjCSO1aTLS/S4KJ5blSm9nq90fre82lBamnK', false, 0);
INSERT INTO employee(firstname, lastname, username, passwordhash, isadmin, wrongPasswordCounter) VALUES('Jennifer', 'Fuerst', 'j.fuerst', '$2a$10$8WiKEL99icp/o/yRZkjCSO1aTLS/S4KJ5blSm9nq90fre82lBamnK', true, 1);
INSERT INTO employee(firstname, lastname, username, passwordhash, isadmin, wrongPasswordCounter) VALUES('Janina', 'Scholz', 'j.scholz', '$2a$10$8WiKEL99icp/o/yRZkjCSO1aTLS/S4KJ5blSm9nq90fre82lBamnK', false, 4);
INSERT INTO employee(firstname, lastname, username, passwordhash, isadmin, wrongPasswordCounter) VALUES('Jakob', 'Scholz', 'ja.scholz', '$2a$10$8WiKEL99icp/o/yRZkjCSO1aTLS/S4KJ5blSm9nq90fre82lBamnK', false, 0);
COMMIT